logging.level.root=info
spring.main.banner-mode=off
spring.config.import=optional:info/my_info.properties
# for h2 mem run on linux
# spring.datasource.url=jdbc:h2:mem:database
# or access on current project (on linux)
#spring.datasource.url=jdbc:h2:file:/home/ttknp/spring-boot-projects/spring-boot-crud-h2-aop-basic/db
# windows
spring.datasource.url=jdbc:h2:file:B:/practice-java-one-jetbrains/learn-spring-boot-and-spring-beans/spring-boot-crud-h2-aop-basic/db
spring.datasource.driverClassName=${H2.DRIVER}
spring.datasource.username=${H2.USERNAME}
spring.datasource.password=${H2.PASSWORD}
spring.jpa.database-platform=${H2.JPA.PLATFORM}

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# For access h2 console on linux
# spring.h2.console.settings.web-allow-others=true